# =======================================================================================================================================================================
# Verify and deploy configure-build
# =======================================================================================================================================================================
name: configure-build
on:
  push:
    # This prevents tag pushes from triggering this workflow
    branches: ['*']
  release:
    types: [published]
env:
  GIT_ADVICE: 0
jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      # Needed to bump tags
      contents: write
    steps:
      # ----------------------------------------------------------------------- Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------------------------------------- Setup tools
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # ----------------------------------------------------------------------- Build action
      - name: Install action dependencies
        run: npm ci --ignore-scripts

      - name: Verify TypeScript
        run: npm run verify

      - name: Build main entrypoint
        run: npm run build

      # ----------------------------------------------------------------------- Verify nothing changed
      # Developers are expected to push the updated `dist` folder with every commit as this will
      # later be required for testing and allows using intermediat commits on GitHub Actions when
      # it is necessary.
      - name: Verify dist folder was up-to-date
        id: verify-dist
        run: |
          git add . --intent-to-add --ignore-removal
          git diff --name-status --exit-code

      - name: Upload artifacts for debugging
        if: steps.verify-dist.outcome != 'success' && always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**

      # ----------------------------------------------------------------------- Deploy
      - name: Bump major version tag
        if: github.event_name == 'release'
        run: node .github/workflows/bump-tag.mjs
        env:
          TAG: ${{github.event.release.tag_name}}
